name: Benchmark

on: push

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2023

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          version-file: ./2023/.tool-versions
          version-type: strict

      - name: Setup
        run: mix do deps.get, compile

      - name: Benchmark
        run: mix run lib/day11/benchmark.exs
